import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Box,
  Button,
  Checkbox,
  FormControl,
  FormControlLabel,
  FormLabel,
  Radio,
  RadioGroup,
  TextField,
} from '@mui/material'
import styles from '../styles/Home.module.css'
import * as api from '../api/index'

const Home: NextPage = () => {
  const [email, setEmail] = useState('')
  const [bitkubAccount, setBtkubAccount] = useState('')
  const [phone, setPhone] = useState('')
  const [waitlist, setWaitlist] = useState(false)
  const [subscribe, setSubscribe] = useState(false)

  const handleSubmit = async () => {
    let form = {
      email: email,
      bitkub_account: Boolean(bitkubAccount),
      phone: phone,
      waitlist: waitlist,
      subscribe: subscribe,
    }

    const rawResponse = await fetch('/api/submit', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(form),
    })
    const content = await rawResponse.json()

    setEmail('')
    setBtkubAccount('')
    setPhone('')
    setWaitlist(false)
    setSubscribe(false)

    alert(content.data.tableRange)
    // const res = await api.submitForm(JSON.stringify(form))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Sheets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box
          component="form"
          sx={{
            width: '25%',
            display: 'flex',
            flexDirection: 'column',
            gap: 1,
          }}
          noValidate
          autoComplete="off"
        >
          <TextField
            required
            type="email"
            label="Email"
            placeholder="example@gmail.com"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
          />
          <FormControl>
            <FormLabel>Bitkub Account</FormLabel>
            <RadioGroup
              value={bitkubAccount}
              onChange={(event) => setBtkubAccount(event.target.value)}
            >
              <FormControlLabel value="true" control={<Radio />} label="True" />
              <FormControlLabel
                value="false"
                control={<Radio />}
                label="False"
              />
            </RadioGroup>
          </FormControl>
          <TextField
            required
            type="tel"
            label="Phone"
            placeholder="0987654321"
            value={phone}
            onChange={(event) => setPhone(event.target.value)}
          />
          <FormControl>
            <FormControlLabel
              control={
                <Checkbox
                  checked={waitlist}
                  onChange={(event) => setWaitlist(event.target.checked)}
                />
              }
              label="Waitlist"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={subscribe}
                  onChange={(event) => setSubscribe(event.target.checked)}
                />
              }
              label="Subscribe"
            />
          </FormControl>
          <Button variant="contained" onClick={handleSubmit}>
            Submit Form
          </Button>
        </Box>
      </main>
    </div>
  )
}

export default Home
